# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
# extra_config_files: /etc/wazo-ui/conf.d/

# Change the log level to debug level.
# debug: false

# # Log file.
# log_filename: /var/log/wazo-ui.log
# 
# # PID file.
# pid_filename: /run/wazo-ui/wazo-ui.pid
# 
# https:
#   listen: 0.0.0.0
#   port: 9296
#   certificate: /usr/share/xivo-certs/server.crt
#   private_key: /usr/share/xivo-certs/server.key
# 
# amid:
#   host: localhost
#   port: 9491
#   prefix: None
#   https: false
# 
# auth:
#   host: localhost
#   port: 9497
#   prefix: None
#   https: false
# 
# call-logd:
#   host: localhost
#   port: 9298
#   verify_certificate: /usr/share/xivo-certs/server.crt
# 
# confd:
#   host: localhost
#   port: 9486
#   verify_certificate: /usr/share/xivo-certs/server.crt
# 
# dird:
#   host: localhost
#   port: 9489
#   verify_certificate: /usr/share/xivo-certs/server.crt
# 
# plugind:
#   host: localhost
#   port: 9503
#   verify_certificate: /usr/share/xivo-certs/server.crt
# 
# provd:
#   host: localhost
#   port: 8666
#   verify_certificate: /usr/share/xivo-certs/server.crt
# 
# webhookd:
#   host: localhost
#   port: 9300
#   verify_certificate: /usr/share/xivo-certs/server.crt
#
# websocketd:
#   host: null  # populated with browser url
#   port: 443
#   prefix: /api/websocketd
#   verify_certificate: False
